routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Auth::guest()) {
        return redirect()->route('login');
    } else {
        if (Auth::user()->role == "admin1" || Auth::user()->role == "admin2") {
            return redirect()->route('administrator.dashboard');
        } else {
            return redirect()->route('agency.dashboard');
        }
    }
});

Auth::routes();

Route::group(['prefix' => '/administrator', 'as' => 'administrator.', 'middleware' => []], function () {
    // dashboard
    Route::get('/', 'AdministratorController@dashboard')->name('dashboard');

    // profile
    Route::match(['get', 'post'], '/profile', 'AdministratorController@profile')->name('profile');

    // change password
    Route::post('/change-password', 'AdministratorController@changePassword')->name('changePassword');

    // requirement type
    Route::resource('/requirement-types', 'RequirementTypeController');
    // add biodata to the requirement type
    Route::post('/requirement-types/{requirement_type}/add-biodata', 'RequirementTypeController@addBiodata')->name('requirement-types.addBiodata');
    Route::delete('/requirement-types/{requirement_type}/remove-biodata', 'RequirementTypeController@removeBiodata')->name('requirement-types.removeBiodata');
    // update order biodata
    Route::put('/requirement-types/{requirement_type}/update-order-biodata', 'RequirementTypeController@updateOrderBiodata')->name('requirement-types.updateOrderBiodata');

    // biodatas
    Route::resource('/biodatas', 'BiodataController');
    // add requirement type to the biodata
    Route::post('/biodatas/{biodata}/add-requirement-type', 'BiodataController@addRequirementType')->name('biodatas.addRequirementType');
    Route::delete('/biodatas/{biodata}/remove-requirement-type', 'BiodataController@removeRequirementType')->name('biodatas.removeRequirementType');

    // requirement form
    Route::resource('/requirement-types/{requirement_type}/requirement-forms', 'RequirementFormController');

    // agencies
    Route::resource('/agencies', 'AgencyController');
    // agency reset password
    Route::post('/agencies/{agency}/reset-password', 'AgencyController@resetPassword')->name('agencies.resetPassword');

    // requirement
    Route::resource('/requirement-types/{requirement_type}/requirements', 'RequirementController');
    Route::get('/requirement-types/{requirement_type}/requirements/agencies/{agency}', 'RequirementController@filterByAgency')->name('requirements.filterByAgency');
	Route::get('/requirement-types/{requirement_type}/requirements/by/all', 'RequirementController@byAll')->name('requirements.byAll');

    // requirement verify
    Route::post('/requirements/{requirement}/verify', 'RequirementController@verify')->name('requirements.verify')->middleware('admin1');
    // requirement finish
    Route::post('/requirements/{requirement}/finish', 'RequirementController@finish')->name('requirements.finish')->middleware('admin2');
    // requirement print
    Route::get('/requirements/{requirement}/print', 'RequirementController@print')->name('requirements.print');

});

Route::group(['prefix' => '/agency', 'as' => 'agency.', 'middleware' => ['auth', 'agency']], function () {
    // dashboard
    Route::get('/', 'AgencyController@dashboard')->name('dashboard');

    // guide
    Route::get('/guide', 'AgencyController@guide')->name('guide');

    // profile
    Route::match(['get', 'post'], '/profile', 'AgencyController@profile')->name('profile');

    // change password
    Route::post('/change-password', 'AgencyController@changePassword')->name('changePassword');

    // biodata
    Route::resource('/requirement-types/{requirement_type}/requirements', 'BiodataPostController');

    // requirement post
    Route::resource('/requirement-type/{requirement_type}/requirements/{requirement}/requirement-posts', 'RequirementPostController');

    // requirement sent
    Route::post('/requirements/{requirement}/sent', 'BiodataPostController@sent')->name('requirements.sent');
});

app/Agency.php
<?php

namespace App;

use GoldSpecDigital\LaravelEloquentUUID\Database\Eloquent\Model;

class Agency extends Model
{
    public $incrementing = false;
    protected $keyType = 'string';
    //
    protected $guarded = [];

    public function user () {
        return $this->hasOne('App\User');
    }

    public function requirements () {
        return $this->hasMany('App\Requirement');
    }
}

app/Http/Controllers/AgencyController.php
<?php

namespace App\Http\Controllers;

use App\Agency;
use App\Requirement;
use App\User;
use Faker\Factory;
use Illuminate\Http\Request;
use Validator;
use App\RequirementType;
use Auth;
use Illuminate\Support\Facades\Hash;
use App\Rules\MatchOldPassword;

class AgencyController extends Controller
{
public function __construct(Agency $agency, RequirementType $requirementType, Requirement $requirement)
    {
        $this->agency = $agency;
        $this->requirementType = $requirementType;
        $this->requirement = $requirement;
    }

    public function dashboard () {
        $requirementTypes = $this->requirementType->get();

        $pie = [
            Auth::user()->agency->requirements()->whereStatus(1)->count(),
            Auth::user()->agency->requirements()->whereStatus(2)->count(),
            Auth::user()->agency->requirements()->whereStatus(3)->count(),
            Auth::user()->agency->requirements()->whereStatus(4)->count()
        ];
        $pie = json_encode($pie);

        $now = date('Y-m-d');
        $line = [];
        $labels = [];
        for ($i = 7; $i > 0; $i--) {
            $date = date('Y-m-d', strtotime('-' . $i . ' days', strtotime($now)));
            $line[] = Auth::user()->agency->requirements()->whereDate('created_at', '=', $date)->count();
            $labels[] = dateLetter($date);
        }
        $line = json_encode($line);
        $labels = json_encode($labels);

        return view('agency.dashboard',[
            'requirementTypes' => $requirementTypes,
            'pie' => $pie,
            'line' => $line,
            'labels' => $labels
        ]);
    }

    public function guide () {
        return view('agency.guide');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $agencies = $this->agency->orderBy('created_at', 'desc')->get();

        //
        return view('agency.index', [
            'agencies' => $agencies
        ]);
    }

    public function profile (Request $request) {
        if ($request->isMethod('post'))
            $this->updateProfile($request);

        $activities = Auth::user()->agency->requirements()->get();

        $results = [];
        $typeDate = ['created_at', 'sent_at', 'first_verify_at', 'second_verify_at'];
        foreach ($activities as $requirement) {

            foreach (range(1, $requirement->status) as $key => $i) {
                $result = new \stdClass();
                $result->datetime = $requirement[$typeDate[$key]];
                $result->status = $i;
                $result->requirement = $requirement;
                $results[] = $result;
            }

        }

        $results = collect($results)->sortByDesc(function ($activity, $key) {
            return $activity->datetime;
        })->values()->toArray();

        return view('agency.profile', [
            'activities' => $results
        ]);
    }

    public function updateProfile ($request) {
        // validations
        $validation = Validator::make($request->all(), [
            'username' => 'required|unique:users,username,' . Auth::user()->id,
            'agency_email' => 'required|unique:agencies,email,' . Auth::user()->agency->id,
            'agency_name' => 'required'
        ]);

        // if validation fails
        if ($validation->fails())
            return redirect()->back()->withErrors($validation)->withInput($request->all());

        // if validation success
        Auth::user()->agency->update([
            'email' => $request->agency_email,
            'name' => $request->agency_name
        ]);
        $action = Auth::user()->update([
            'username' => $request->username
        ]);

        // if action success
        if ($action) {
            return redirect()->back()->with('msg', 'Berhasil diperbarui');
        } else {
            return redirect()->back()->with('msgError', 'Gagal diperbarui. Silahkan coba kembali');
        }
    }

    function changePassword (Request $request) {
        // validations
        $validation = Validator::make($request->all(), [
            'old_password' => ['required', new MatchOldPassword],
            'new_password' => 'required|min:8',
            'new_password_confirmation' => 'required|same:new_password'
        ]);

        // if validation fails
        if ($validation->fails())
            return redirect()->back()->withErrors($validation)->withInput($request->all());

        // if validation success
        Auth::user()->agency->update([
            'password' => NULL
        ]);
        $action = Auth::user()->update([
            'password' => Hash::make($request->new_password)
        ]);

        // if action success
        if ($action) {
            return redirect()->back()->with('msg', 'Password berhasil diperbarui');
        } else {
            return redirect()->back()->with('msgError', 'Password gagal diperbarui. Silahkan coba kembali');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('agency.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // validations
        $validation = Validator::make($request->all(), [
            'name' => 'required'
        ]);

        // validation fails
        if ($validation->fails())
            return redirect()->back()->withInput($request->all())->withErrors($validation);

        // validation success
        $username = Factory::create()->regexify('[A-Za-z0-9]{8,8}');
        $password = strtoupper(Factory::create()->regexify('[0-9]{8,8}'));

        $action = $this->agency->create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => $password
        ]);
        $action->user()->create([
            'username' => strtoupper($username),
            'password' => bcrypt($password),
            'role' => 'agency'
        ]);

        // if action success
        if ($action) {
            return redirect()->back()->with('msg', 'Dinas berhasil ditambahkan');
        } else {
            return redirect()->back()->with('msgError', 'Dinas gagal ditambahkan. Silahkan coba kembali.');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Agency  $agency
     * @return \Illuminate\Http\Response
     */
    public function show(Agency $agency)
    {
        //
        return view('agency.show', [
            'agency' => $agency
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Agency  $agency
     * @return \Illuminate\Http\Response
     */
    public function edit(Agency $agency)
    {
        //
        return view('agency.form', [
            'agency' => $agency
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Agency  $agency
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Agency $agency)
    {
        //
        // validations
        $validation = Validator::make($request->all(), [
            'name' => 'required'
        ]);

        // validation fails
        if ($validation->fails())
            return redirect()->back()->withInput($request->all())->withErrors($validation);

        // validation success
        $action = $agency->update([
            'name' => $request->name,
            'email' => $request->email
        ]);

        // if action success
        if ($action) {
            return redirect()->back()->with('msg', 'Dinas berhasil diperbarui');
        } else {
            return redirect()->back()->with('msgError', 'Dinas gagal diperbarui. Silahkan coba kembali.');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Agency  $agency
     * @return \Illuminate\Http\Response
     */
    public function destroy(Agency $agency)
    {
        // validations
        if ($agency->requirements->where('status', '!=', 1)->count() > 0) {
            return response()->json(['msg' => 'Dinas ini memiliki data biodata persyaratan. Hapus biodata persyaratan terlebih dahulu untuk menghapus.'], 401);
        }

        // validation success
        $action = $agency->delete();

        // if action success
        if ($action) {
            return response()->json(['msg' => 'Dinas berhasil dihapus'], 200);
        } else {
            return response()->json(['msg' => 'Dinas gagal dihapus. Silahkan coba kembali.'], 404);
        }
    }

    public function resetPassword (Request $request, Agency $agency) {
        // define faker
        $faker = Factory::create();

        // generate password
        $realPassword = $faker->regexify('[0-9]{8,8}');
        $newPassword = Hash::make($realPassword);

        // update password
        $agency->update([
            'password' => $realPassword
        ]);
        $action = $agency->user->update([
            'password' => $newPassword
        ]);

        // if action success
        if ($action) {
            return redirect()->back()->with('msg', 'Password berhasil direset.');
        } else {
            return redirect()->back()->with('msgError', 'Password gagal direset.');
        }
    }
}

resources/views/agency/form.blade.php
@php
    $state = isset($agency);
    $theme = $state ? 'warning' : 'primary';
@endphp

@extends('layouts.master')

@section('title')
    List Dinas
@endsection

@section('agency')
    active
@endsection

@section('menu')
    <i class="fa fa-landmark"></i> Dinas
@endsection

@section('breadcumb')
    <li class="breadcrumb-item"><a href="{{route('administrator.dashboard')}}">Dashboard</a></li>
    <li class="breadcrumb-item"><a href="{{route('administrator.requirement-types.index')}}">List Tipe Dinas</a></li>
    <li class="breadcrumb-item active">Tambah Dinas</li>
@endsection

@section('content')
    <div class="container-fluid">
        <div class="jumbotron d-flex align-items-center justify-content-center">
            <img src="{{asset('assets/img/illustration-3.svg')}}" class="illustration mr-5" alt="">
            <div class="col-md-5">
                <h4 class="mb-3">{{($state ? 'Edit' : 'Tambah') . " Form Dinas"}}</h4>
                <p style="margin-bottom: 0px;" class="text-muted">
                    Isi formulir dibawah sesuai dengan form dinas. Kemudian tekan tombol <span class="text-info">Simpan</span> untuk menyimpan data Dinas.
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="card card-{{$theme}}">
                    <div class="card-header">
                        <h3 class="card-title">Form {{ $state ? 'edit dinas' : 'dinas baru' }}</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form class="form-horizontal" action="{{route('administrator.agencies.' . ($state ? 'update' : 'store'), $state ? ['agency' => $agency->id] : [])}}" method="post">
                        @csrf
                        @if($state)
                            @method('put')
                        @endif
                        <div class="card-body">

                            @if(session('msg'))
                                <div class="alert alert-success">
                                    {{session('msg')}}
                                </div>
                            @elseif(session('msgError'))
                                <div class="alert alert-danger">
                                    {{session('msgError')}}
                                </div>
                            @endif

                            <div class="form-group row">
                                <label for="inputEmail3" class="col-sm-2 col-form-label">Nama Dinas</label>
                                <div class="col-sm-10">
                                    <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" id="inputEmail3" placeholder="Nama Dinas" value="{{old('name') ? old('name') : ($state ? $agency->name : '')}}">
                                    @if($errors->first('name'))
                                    <div class="invalid-feedback">
                                        {{$errors->first('name')}}
                                    </div>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="inputPassword3" class="col-sm-2 col-form-label">Email</label>
                                <div class="col-sm-10">
                                    <input type="email" class="form-control" id="inputPassword3" placeholder="Email" name="email" value="{{old('email') ? old('email') : ($state ? $agency->email: '') }}">
                                    <small id="passwordHelpBlock" class="form-text text-muted">
                                        Email bersifat optional. Dengan mengisi email, system dapat mengirimkan notifikasi.
                                    </small>
                                </div>
                            </div>
                            <div class="form-group row form-submit">
                                <div class="col-md-2"></div>
                                <div class="col-md-10">
                                    <button type="submit" class="btn btn-{{$theme}} mr-2"><i class="fa fa-save mr-2"></i> Simpan</button>
                                    <a href="{{route('administrator.agencies.index')}}" class="btn">Kembali</a>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-body -->
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('css')
@endsection

@section('js')
@endsection

resources/views/agency/index.blade.php
@extends('layouts.master')

@section('title')
    List Dinas
@endsection

@section('agency')
    active
@endsection

@section('menu')
    <i class="fa fa-landmark"></i> Dinas
@endsection

@section('breadcumb')
    <li class="breadcrumb-item"><a href="{{route('administrator.dashboard')}}">Dashboard</a></li>
    <li class="breadcrumb-item active">Dinas</li>
@endsection

@section('content')
    <div class="container-fluid">
        @if(session('msg'))
            <div class="alert alert-success">
                {{session('msg')}}
            </div>
        @elseif(session('msgError'))
            <div class="alert alert-danger">
                {{session('msgError')}}
            </div>
        @elseif($errors->any())
            <div class="alert alert-danger">
                Opps.. Ada yang error! <br>
                @foreach($errors->all() as $error)
                    {{$error}} <br>
                @endforeach
            </div>
        @endif

            <div class="jumbotron d-flex align-items-center justify-content-center">
                <img src="{{asset('assets/img/ill-list.svg')}}" class="illustration mr-5" alt="">
                <div class="col-md-5">
                    <h4 class="mb-3">List Dinas</h4>
                    <p style="margin-bottom: 0px;" class="text-muted">
                        Dibawah kamu dapat melihat list dinas. Kamu dapat menambah, mengedit, menghapus, mereset password serta melihat detail dari dinas.
                    </p>
                </div>
            </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header align-items-center justify-content-between" style="display: grid; grid-template-columns: repeat(2, auto)">
                        <h3 class="card-title">List Dinas</h3>
                        <a href="{{route('administrator.agencies.create')}}" class="btn text-bg text-bold text-primary"><i class="fa fa-plus-circle"></i> Tambah dinas</a>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example" class="table table-striped dt-responsive nowrap" style="width: 100%">
                            <thead>
                            <tr>
                                <th>Nama Dinas</th>
                                <th class="text-center">Jumlah Persyaratan</th>
                                <th>Email</th>
                                <th>Username</th>
                                <th>Password</th>
                                <th class="text-center">Aksi</th>
                            </tr>
                            </thead>
                            <tbody>
                                @foreach($agencies as $agency)
                                    <tr>
                                        <td>{{$agency->name}}</td>
                                        <td class="text-center">{{$agency->requirements->where('status', '!=', 1)->count()}}</td>
                                        <td>{{$agency->email ? $agency->email : '-'}}</td>
                                        <td>{{$agency->user->username}}</td>
                                        <td>{!! $agency->password ? $agency->password : '<span class="badge badge-info">password telah diganti oleh dinas</span>' !!}</td>
                                        <td class="text-center">
                                            <a href="{{route('administrator.agencies.destroy', ['agency' => $agency->id])}}" class="text-danger mr-3 btn-delete" title="Delete">
                                                <i class="fa fa-trash mr-1"></i> Delete
                                            </a>
                                            <a href="{{route('administrator.agencies.edit', ['agency' => $agency->id])}}" class="text-warning mr-3" title="Edit">
                                                <i class="fa fa-edit mr-1"></i> Edit
                                            </a>
                                            <a href="{{route('administrator.agencies.resetPassword', ['agency' => $agency->id])}}" class="btn btn-xs btn-primary btn-reset" title="Detail">
                                                <i class="fa fa-lock mr-1"></i> Reset Password
                                            </a>
                                            <a href="{{route('administrator.agencies.show', ['agency' => $agency->id])}}" class="btn btn-xs btn-default ml-2" title="Lihat Semua Biodata" data-toggle="tooltip">
                                                 Lihat Biodata <i class="fa fa-arrow-right ml-1"></i>
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
        </div>
    </div>

    <form class="modal fade" id="modal-default" action="" method="post">
        @csrf
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Reset Password</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body d-flex justify-content-center">
                    <button type="submit" class="btn btn-primary mr-2"><i class="fa fa-lock mr-2"></i> Reset sekarang</button>
                    <button type="button" class="btn text-danger" data-dismiss="modal">Batalkan</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </form>
    <!-- /.modal -->
@endsection

@section('css')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{asset('assets/plugins/datatables-bs4/css/dataTables.bootstrap4.css')}}">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.1/css/buttons.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.1/css/buttons.bootstrap4.min.css">
    <link rel="stylesheet" href="{{asset('assets/plugins/datatables/responsive.bootstrap4.min.css')}}">
@endsection

@section('js')
    <!-- DataTables -->
    <script src="{{asset('assets/plugins/datatables/jquery.dataTables.js')}}"></script>
    <script src="{{asset('assets/plugins/datatables-bs4/js/dataTables.bootstrap4.js')}}"></script>
    <script src="{{asset('assets/plugins/datatables/dataTables.responsive.min.js')}}"></script>
    <script src="{{asset('assets/plugins/datatables/responsive.bootstrap4.min.js')}}"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.print.min.js"></script>
    <!-- page script -->
    <script>
        $(function () {
            $('#example').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    'copy', 'csv', 'excel', 'pdf', 'print'
                ]
            });
            $("#example1").DataTable({
                dom: 'Bfrtip',
                buttons: [
                    'copy', 'csv', 'excel', 'pdf', 'print'
                ]
            });
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
            });

            $('.btn-reset').click(function (e) {
                e.preventDefault();

                let url = $(this).attr('href');
                $('#modal-default').attr('action', url);
                $('#modal-default').modal('show');
            });
        });
    </script>
@endsection