routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Auth::guest()) {
        return redirect()->route('login');
    } else {
        if (Auth::user()->role == "admin1" || Auth::user()->role == "admin2") {
            return redirect()->route('administrator.dashboard');
        } else {
            return redirect()->route('agency.dashboard');
        }
    }
});

Auth::routes();

Route::group(['prefix' => '/administrator', 'as' => 'administrator.', 'middleware' => []], function () {
    // dashboard
    Route::get('/', 'AdministratorController@dashboard')->name('dashboard');

    // profile
    Route::match(['get', 'post'], '/profile', 'AdministratorController@profile')->name('profile');

    // change password
    Route::post('/change-password', 'AdministratorController@changePassword')->name('changePassword');

    // requirement type
    Route::resource('/requirement-types', 'RequirementTypeController');
    // add biodata to the requirement type
    Route::post('/requirement-types/{requirement_type}/add-biodata', 'RequirementTypeController@addBiodata')->name('requirement-types.addBiodata');
    Route::delete('/requirement-types/{requirement_type}/remove-biodata', 'RequirementTypeController@removeBiodata')->name('requirement-types.removeBiodata');
    // update order biodata
    Route::put('/requirement-types/{requirement_type}/update-order-biodata', 'RequirementTypeController@updateOrderBiodata')->name('requirement-types.updateOrderBiodata');

    // biodatas
    Route::resource('/biodatas', 'BiodataController');
    // add requirement type to the biodata
    Route::post('/biodatas/{biodata}/add-requirement-type', 'BiodataController@addRequirementType')->name('biodatas.addRequirementType');
    Route::delete('/biodatas/{biodata}/remove-requirement-type', 'BiodataController@removeRequirementType')->name('biodatas.removeRequirementType');

    // requirement form
    Route::resource('/requirement-types/{requirement_type}/requirement-forms', 'RequirementFormController');

    // agencies
    Route::resource('/agencies', 'AgencyController');
    // agency reset password
    Route::post('/agencies/{agency}/reset-password', 'AgencyController@resetPassword')->name('agencies.resetPassword');

    // requirement
    Route::resource('/requirement-types/{requirement_type}/requirements', 'RequirementController');
    Route::get('/requirement-types/{requirement_type}/requirements/agencies/{agency}', 'RequirementController@filterByAgency')->name('requirements.filterByAgency');
	Route::get('/requirement-types/{requirement_type}/requirements/by/all', 'RequirementController@byAll')->name('requirements.byAll');

    // requirement verify
    Route::post('/requirements/{requirement}/verify', 'RequirementController@verify')->name('requirements.verify')->middleware('admin1');
    // requirement finish
    Route::post('/requirements/{requirement}/finish', 'RequirementController@finish')->name('requirements.finish')->middleware('admin2');
    // requirement print
    Route::get('/requirements/{requirement}/print', 'RequirementController@print')->name('requirements.print');

});

Route::group(['prefix' => '/agency', 'as' => 'agency.', 'middleware' => ['auth', 'agency']], function () {
    // dashboard
    Route::get('/', 'AgencyController@dashboard')->name('dashboard');

    // guide
    Route::get('/guide', 'AgencyController@guide')->name('guide');

    // profile
    Route::match(['get', 'post'], '/profile', 'AgencyController@profile')->name('profile');

    // change password
    Route::post('/change-password', 'AgencyController@changePassword')->name('changePassword');

    // biodata
    Route::resource('/requirement-types/{requirement_type}/requirements', 'BiodataPostController');

    // requirement post
    Route::resource('/requirement-type/{requirement_type}/requirements/{requirement}/requirement-posts', 'RequirementPostController');

    // requirement sent
    Route::post('/requirements/{requirement}/sent', 'BiodataPostController@sent')->name('requirements.sent');
});

app/Http/Controllers/RequirementTypeController.php
<?php

namespace App\Http\Controllers;

use App\Biodata;
use App\RequirementType;
use Validator;
use Illuminate\Http\Request;

class RequirementTypeController extends Controller
{
    public function __construct(RequirementType $rt, Biodata $biodata)
    {
        $this->rt = $rt;
        $this->biodata = $biodata;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $requirement_types = $this->rt->orderBy('id', 'DESC')->get();

        //
        return view('requirement-type.index', [
            'requirement_types' => $requirement_types
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('requirement-type.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // validations
        $validation = Validator::make($request->all(), [
            'name' => 'required',
            'print_file' => 'mimes:rtf'
        ]);

        // validation fails
        if ($validation->fails())
            return redirect()->back()->withInput($request->all())->withErrors($validation);

        // define abbr
        $abbr = "";
        if ($request->abbr)
            $abbr = $request->abbr;
        else {
            foreach (explode(' ', $request->name) as $word) {
                $abbr .= $word[0];
            }
        }
        $abbr = strtoupper($abbr);

        // upload file template
        $print_file = NULL;
        if ($request->file('print_file')) {
            $print_file = $request->file('print_file');
            $print_file = $print_file->store('public/letter-templates/');
        }

        // validation success
        $action = $this->rt->create([
            'name' => $request->name,
            'abbr' => $abbr,
            'print_file' => $print_file
        ]);

        // if action success
        if ($action) {
            return redirect()->route('administrator.requirement-forms.index', ['requirement_type' => $action->id])->with('msg', 'Tipe persyaratan berhasil ditambahkan');
        } else {
            return redirect()->back()->with('msgError', 'Tipe persyaratan gagal ditambahkan. Silahkan coba kembali.');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\RequirementType  $requirementType
     * @return \Illuminate\Http\Response
     */
    public function show(RequirementType $requirementType)
    {
        //
        return view('requirement-type.show', [
            'requirementType' => $requirementType
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\RequirementType  $requirementType
     * @return \Illuminate\Http\Response
     */
    public function edit(RequirementType $requirementType)
    {
        //
        return view('requirement-type.form', [
            'requirement_type' => $requirementType
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\RequirementType  $requirementType
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, RequirementType $requirementType)
    {
        // validations
        $validation = Validator::make($request->all(), [
            'name' => 'required',
            'print_file' => 'mimes:rtf'
        ]);

        // validation fails
        if ($validation->fails())
            return redirect()->back()->withInput($request->all())->withErrors($validation);

        // define abbr
        $abbr = "";
        if ($request->abbr)
            $abbr = $request->abbr;
        else {
            foreach (explode(' ', $request->name) as $word) {
                $abbr .= $word[0];
            }
        }
        $abbr = strtoupper($abbr);

        $print_file = $requirementType->print_file;
        if ($request->file('print_file')) {
            $print_file = $request->file('print_file');
            $print_file = $print_file->store('public/letter-templates/');
        }

        // validation success
        $action = $requirementType->update([
            'name' => $request->name,
            'abbr' => $abbr,
            'print_file' => $print_file
        ]);

        // if action success
        if ($action) {
            return redirect()->back()->with('msg', 'Tipe persyaratan berhasil diperbarui');
        } else {
            return redirect()->back()->with('msgError', 'Tipe persyaratan gagal diperbarui. Silahkan coba kembali.');
        }
    }

    public function updateOrderBiodata (Request $request, RequirementType $requirementType) {
        foreach ($request->list as $i => $list) {
            $requirementType->biodatas()->updateExistingPivot($list, [
                'order' => $i+1
            ]);
        }
    }

    public function addBiodata (Request $request, RequirementType $requirementType) {
        $order = 1;
        if ($requirementType->biodatas()->count() > 0) {
            $last = $requirementType->biodatas()->orderBy('requirement_type_biodata.order', 'desc')->first()->pivot->order;
            $order = $last + 1;
        }

        $requirementType->biodatas()->attach($request->biodata_id, ['order' => $order]);

        return [
            'method' => 'add',
            'data' => $this->biodata->find($request->biodata_id)
        ];
    }

    public function removeBiodata (Request $request, RequirementType $requirementType) {
        $requirementType->biodatas()->detach($request->biodata_id);

        return [
            'method' => 'remove'
        ];
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\RequirementType  $requirementType
     * @return \Illuminate\Http\Response
     */
    public function destroy(RequirementType $requirementType)
    {
        // validations
        if ($requirementType->requirements->count() > 0) {
            return response()->json(['message' => 'Tipe persyaratan ini memiliki data biodata persyaratan dari beberapa dinas. Hapus biodata persyaratan terlebih dahulu untuk menghapus.'], 401);
        }

        // validation success
        $action = $requirementType->delete();

        // if action success
        if ($action) {
            return response()->json(['msg' => 'Tipe persyaratan berhasil dihapus'], 200);
        } else {
            return response()->json(['msg' => 'Tipe persyaratan gagal dihapus. Silahkan coba kembali.'], 404);
        }
    }
}

resources/views/requirement-type/index.blade.php
@extends('layouts.master')

@section('title')
    List Tipe Persyaratan
@endsection

@section('requirement-type')
    active
@endsection

@section('breadcumb')
    <li class="breadcrumb-item"><a href="{{route('administrator.dashboard')}}">Dashboard</a></li>
    <li class="breadcrumb-item active">Tipe Persayaratan</li>
@endsection

@section('menu')
    <i class="fa fa-boxes"></i> Tipe Persyaratan
@endsection

@section('content')
    <div class="container-fluid">
        <div class="jumbotron d-flex align-items-center justify-content-center">
            <img src="{{asset('assets/img/illustration-5.svg')}}" class="illustration mr-5" alt="">
            <div class="col-md-5">
                <h4 class="mb-3"><span style="font-weight: normal">Tipe persyaratan</h4>
                <p style="margin-bottom: 0px;" class="text-muted">Dibawah ini merupakan list tipe persyaratan yang dapat dinas isi. Kamu dapat membuatnya dengan menekan tombol <span class="text-info">Tambah Persyaratan</span>. Kemudian Kamu dapat melihat detail form persyaratan dari tipe persyaratan dengan menekan tombol <span class="text-info">Detail</span>, dan kamu juga dapat mengatur form biodata serta urutannya dengan menekan tombol <span class="text-info">Atur Biodata</span>.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header align-items-center justify-content-between" style="display: grid; grid-template-columns: repeat(2, auto)">
                        <h3 class="card-title">List Tipe Persyaratan</h3>
                        <a href="{{ route('administrator.requirement-types.create') }}" class="btn btn-primary"><i class="fa fa-plus-circle mr-1"></i> Tambah Persyaratan</a>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example1" class="table table-striped">
                            <thead>
                            <tr>
                                <th>Nama Persyaratan</th>
                                <th class="text-center">Jml. Form</th>
                                <th class="text-center">Jml. Biodata</th>
                                <th class="text-center">Surat</th>
                                <th class="text-center">Aksi</th>
                            </tr>
                            </thead>
                            <tbody>
                                @foreach($requirement_types as $rt)
                                    <tr>
                                        <td>{{$rt->name}}</td>
                                        <td class="text-center">
                                            <a href="{{route('administrator.requirement-forms.index', ['requirement_type' => $rt->id])}}" class="text-info font-weight-bold">
                                                {{$rt->requirement_forms->count()}}
                                            </a>
                                        </td>
                                        <td class="text-center">
                                            <a href="" class="text-info font-weight-bold">
                                                {{$rt->biodatas->count()}}
                                            </a>
                                        </td>
                                        <td class="text-center">
                                            @if($rt->print_file)
                                                <span class="badge badge-success">
                                                    Ada
                                                </span>
                                            @endif
                                        </td>
                                        <td class="text-center">
                                            <a href="{{route('administrator.requirement-types.show', ['requirement_type' => $rt->id])}}" class="btn-xs btn btn-default" title="Atur Biodata" data-toggle="tooltip">
                                                <i class="fa fa-id-card mr-1"></i> Atur Biodata
                                            </a>
                                            <a href="{{route('administrator.requirement-forms.index', ['requirement_type' => $rt->id])}}" class="btn-xs text-info ml-2" title="List formulir" data-toggle="tooltip">
                                                 Detail <i class="fa fa-arrow-right ml-1"></i>
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
        </div>
    </div>
@endsection

@section('css')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{asset('assets/plugins/datatables-bs4/css/dataTables.bootstrap4.css')}}">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.1/css/buttons.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.1/css/buttons.bootstrap4.min.css">
@endsection

@section('js')
    <!-- DataTables -->
    <script src="{{asset('assets/plugins/datatables/jquery.dataTables.js')}}"></script>
    <script src="{{asset('assets/plugins/datatables-bs4/js/dataTables.bootstrap4.js')}}"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.print.min.js"></script>
    <!-- page script -->
    <script>
        $(function () {
            $("#example1").DataTable({
                dom: 'Bfrtip',
                buttons: [
                    'copy', 'csv', 'excel', 'pdf', 'print'
                ]
            });
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
            });
        });
    </script>
@endsection

resources/views/requirement-type/show.blade.php
@extends('layouts.master')

@section('title')
    Pengaturan Form Biodata {{$requirementType->name}}
@endsection

@section('requirement-type')
    active
@endsection

@section('menu')
    <i class="fa fa-user-circle"></i> Pengaturan Form Biodata
@endsection

@section('breadcumb')
    <li class="breadcrumb-item"><a href="{{route('administrator.dashboard')}}">Dashboard</a></li>
    <li class="breadcrumb-item active"><a href="{{route('administrator.requirement-types.index')}}">List Tipe Persayaratan</a></li>
    <li class="breadcrumb-item active"><a href="{{route('administrator.requirement-forms.index', ['requirement_type' => $requirementType->id])}}">{{$requirementType->name}}</a></li>
    <li class="breadcrumb-item active">Pengaturan Form Biodata</li>
@endsection

@section('content')
    <div class="container-fluid">
        @if(session('msg'))
            <div class="alert alert-success">
                {{session('msg')}}
            </div>
        @endif

        <div class="jumbotron d-flex align-items-center justify-content-center">
            <img src="{{asset('assets/img/illustration-13.svg')}}" class="illustration mr-5" alt="">
            <div class="col-md-5">
                <h4 class="mb-3">Atur biodata <span class="text-info">{{$requirementType->name}}</span></h4>
                <p style="margin-bottom: 0px;" class="text-muted">
                    Kamu dapat mengatur urutan form biodata disebelah kiri dengan menekan lalu menahan list biodata, dan arahkan ke posisi yang diinginkan. Kemudian kamu dapat menyeleksi Form biodata yang ingin ditambahkan dengan menceklis data biodata yang ada disebelah kanan.
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-3">
                <div class="card card-default">
                    <div class="card-header">
                        <h3 class="card-title">
                            Urutan Form Biodata
                        </h3>
                    </div>
                    <div class="card-body">
                        <ul class="list-group" id="sortable">
                            @foreach($requirementType->biodatas()->orderBy('requirement_type_biodata.order', 'asc')->get() as $i => $biodata)
                            <li class="list-group-item" data-id="{{$biodata->id}}" style="cursor:grab;">
                                <a href="" class="mr-2 text-muted"><i class="fa fa-arrows-alt-v"></i></a>
                                {{$biodata->name}}
                                <span style="float: right;"></span>
                            </li>
                            @endforeach
                        </ul>
                    </div>
                    <div class="card-footer d-flex text-info">
                        <i class="fa fa-info-circle mr-2"></i> Klik dan seret list form biodata dan pindahkan sesuai dengan diinginkan
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="card card-default">
                    <div class="card-header d-flex align-items-center justify-content-between">
                        <h3 class="card-title">
                            Seleksi Form Biodata
                        </h3>
                        <a href="{{route('administrator.biodatas.create')}}" class="text-right">Tambah form biodata baru <i class="fa fa-arrow-right ml-2"></i></a>
                    </div>
                    <div class="card-body">
                        @foreach(\App\Biodata::orderBy('name', 'asc')->get()->chunk(3) as $biodatas)
                            <div class="row">
                                @foreach($biodatas as $biodata)
                                    <div class="col-md-4 form-group clearfix">
                                        <div class="icheck-primary d-inline">
                                            <input type="checkbox" id="checkbox-{{$biodata->id}}" class="biodata" value="{{$biodata->id}}" {{$biodata->requirement_types()->whereRequirementTypeId($requirementType->id)->first() ? 'checked' : ''}}>
                                            <label for="checkbox-{{$biodata->id}}">
                                            </label>
                                        </div>
                                        {{$biodata->name}}
                                    </div>
                                @endforeach
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('css')
    <!-- iCheck for checkboxes and radio inputs -->
    <link rel="stylesheet" href="{{asset('assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css')}}">
@endsection

@section('js')

    <!-- page script -->
    <script>
        $( function() {
            let token = $('meta[name="csrf-token"]').attr('content');

            $( "#sortable" ).sortable({
                cursor: 'grabbing',
                beforeStop: function (event, ui) {
                    let list = Array.from($('.list-group-item')).map(function (item) {
                        return item.getAttribute('data-id');
                    }).filter(item => item != null);

                    $.ajax({
                        url: '{{route('administrator.requirement-types.updateOrderBiodata', ['requirement_type' => $requirementType->id])}}',
                        method: 'post',
                        data: {_method: 'put', _token: token, list},
                        success: function (response) {
                        },
                        error: function (errors) {
                            alert('error');
                        }
                    })
                }
            });
            $( "#sortable" ).disableSelection();

            $('.biodata').click(function () {
                let url, data = {
                    _token: token,
                    biodata_id: $(this).val()
                };

                if ($(this).is(':checked')) {
                    url = '{{route('administrator.requirement-types.addBiodata', ['requirement_type' => $requirementType->id])}}';
                } else {
                    url = '{{route('administrator.requirement-types.removeBiodata', ['requirement_type' => $requirementType->id])}}';
                    data._method = "DELETE";
                }

                $.ajax({
                    url,
                    method: 'post',
                    data,
                    success: function (response) {
                        if (response.method == "add") {
                            let template = `
                                <li class="list-group-item" data-id="${response.data.id}" style="cursor:grab;">
                                            <a href="" class="mr-2 text-muted"><i class="fa fa-arrows-alt-v"></i></a>
                                            ${response.data.name}
                                    <span style="float: right;"></span>
                                </li>
                            `;

                            $('#sortable').append(template);
                        } else {
                            $(`.list-group-item[data-id="${data.biodata_id}"]`).remove();
                        }
                    },
                    error: function (errors) {
                        alert('error');
                    }
                })
            })
        } );
    </script>
@endsection