routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Auth::guest()) {
        return redirect()->route('login');
    } else {
        if (Auth::user()->role == "admin1" || Auth::user()->role == "admin2") {
            return redirect()->route('administrator.dashboard');
        } else {
            return redirect()->route('agency.dashboard');
        }
    }
});

Auth::routes();

Route::group(['prefix' => '/administrator', 'as' => 'administrator.', 'middleware' => []], function () {
    // dashboard
    Route::get('/', 'AdministratorController@dashboard')->name('dashboard');

    // profile
    Route::match(['get', 'post'], '/profile', 'AdministratorController@profile')->name('profile');

    // change password
    Route::post('/change-password', 'AdministratorController@changePassword')->name('changePassword');

    // requirement type
    Route::resource('/requirement-types', 'RequirementTypeController');
    // add biodata to the requirement type
    Route::post('/requirement-types/{requirement_type}/add-biodata', 'RequirementTypeController@addBiodata')->name('requirement-types.addBiodata');
    Route::delete('/requirement-types/{requirement_type}/remove-biodata', 'RequirementTypeController@removeBiodata')->name('requirement-types.removeBiodata');
    // update order biodata
    Route::put('/requirement-types/{requirement_type}/update-order-biodata', 'RequirementTypeController@updateOrderBiodata')->name('requirement-types.updateOrderBiodata');

    // biodatas
    Route::resource('/biodatas', 'BiodataController');
    // add requirement type to the biodata
    Route::post('/biodatas/{biodata}/add-requirement-type', 'BiodataController@addRequirementType')->name('biodatas.addRequirementType');
    Route::delete('/biodatas/{biodata}/remove-requirement-type', 'BiodataController@removeRequirementType')->name('biodatas.removeRequirementType');

    // requirement form
    Route::resource('/requirement-types/{requirement_type}/requirement-forms', 'RequirementFormController');

    // agencies
    Route::resource('/agencies', 'AgencyController');
    // agency reset password
    Route::post('/agencies/{agency}/reset-password', 'AgencyController@resetPassword')->name('agencies.resetPassword');

    // requirement
    Route::resource('/requirement-types/{requirement_type}/requirements', 'RequirementController');
    Route::get('/requirement-types/{requirement_type}/requirements/agencies/{agency}', 'RequirementController@filterByAgency')->name('requirements.filterByAgency');
	Route::get('/requirement-types/{requirement_type}/requirements/by/all', 'RequirementController@byAll')->name('requirements.byAll');

    // requirement verify
    Route::post('/requirements/{requirement}/verify', 'RequirementController@verify')->name('requirements.verify')->middleware('admin1');
    // requirement finish
    Route::post('/requirements/{requirement}/finish', 'RequirementController@finish')->name('requirements.finish')->middleware('admin2');
    // requirement print
    Route::get('/requirements/{requirement}/print', 'RequirementController@print')->name('requirements.print');

});

Route::group(['prefix' => '/agency', 'as' => 'agency.', 'middleware' => ['auth', 'agency']], function () {
    // dashboard
    Route::get('/', 'AgencyController@dashboard')->name('dashboard');

    // guide
    Route::get('/guide', 'AgencyController@guide')->name('guide');

    // profile
    Route::match(['get', 'post'], '/profile', 'AgencyController@profile')->name('profile');

    // change password
    Route::post('/change-password', 'AgencyController@changePassword')->name('changePassword');

    // biodata
    Route::resource('/requirement-types/{requirement_type}/requirements', 'BiodataPostController');

    // requirement post
    Route::resource('/requirement-type/{requirement_type}/requirements/{requirement}/requirement-posts', 'RequirementPostController');

    // requirement sent
    Route::post('/requirements/{requirement}/sent', 'BiodataPostController@sent')->name('requirements.sent');
});

app/Biodata.php
<?php

namespace App;

use GoldSpecDigital\LaravelEloquentUUID\Database\Eloquent\Model;

class Biodata extends Model
{
    public $incrementing = false;
    protected $keyType = 'string';

    //
    protected $guarded = [];

    public function requirement_types () {
        return $this->belongsToMany('App\RequirementType', 'requirement_type_biodata', 'biodata_id', 'requirement_type_id')
            ->withPivot('order');
    }

    public function biodata_posts () {
        return $this->hasMany('App\BiodataPost');
    }

}

app/Http/Controllers/BiodataController.php
<?php

namespace App\Http\Controllers;

use App\Biodata;
use App\RequirementType;
use Illuminate\Http\Request;
use Auth;
use Validator;

class BiodataController extends Controller
{
    function __construct(Biodata $biodata, RequirementType $requirementType)
    {
        $this->biodata = $biodata;
        $this->requirementType = $requirementType;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $biodatas = $this->biodata->get();
        //
        return view('biodata.index', [
            'biodatas' =>  $biodatas
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        //
        return view('biodata.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // rules
        $rules = [
            'name' => 'required|unique:biodatas,name'
        ];

        if ($request->type == "radio")
            $rules['choices'] = 'required';

        // validations
        $validation = Validator::make($request->all(), $rules);

        // validation fails
        if ($validation->fails())
            return redirect()->back()->withInput($request->all())->withErrors($validation);

        // validation success
        if (!$request->placeholder || empty($request->placeholder))
            $request->placeholder = $request->name;


        // insert
        $action = $this->biodata->create([
            'name' => $request->name,
            'placeholder' => $request->placeholder,
            'type' => $request->type,
            'choices' => $request->choices,
            'attributes' => NULL
        ]);

        // insert requireent type are related
        foreach ($request->requirement_type_biodata as $rtb) {
            $requirementType = $this->requirementType->find($rtb);
            $order = 1;

            if ($requirementType->biodatas()->count() > 0) {
                $last = $requirementType->biodatas()->orderBy('requirement_type_biodata.order', 'desc')->first()->pivot->order;
                $order = $last + 1;
            }

            $action->requirement_types()->attach($rtb, ['order' => $order]);
        }

        // success
        if ($action) {
            return redirect()->back()->with('msg', 'Form Biodata berhasil ditambahkan');
//            return redirect()->route('administrator.biodatas.show', ['biodata' => $action->id])->with('msg', 'Form Biodata berhasil ditambahkan');
        } else {
            return redirect()->back()->with('msgError', 'Form Biodata gagal ditambahkan. Silahkan coba kembali.');
        }

    }

    public function addRequirementType (Request $request, Biodata $biodata) {
        $order = 1;
        if ($biodata->requirement_types()->count() > 0) {
            $last = $biodata->requirement_types()->orderBy('requirement_type_biodata.order', 'desc')->first()->pivot->order;
            $order = $last + 1;
        }

        $biodata->requirement_types()->attach($request->requirement_type_id, ['order' => $order]);

        return [
            'method' => 'add',
            'data' => $this->requirementType->find($request->requirement_type_id),
            'requiremnet _type_id' => $request->requirement_type_id
        ];
    }

    public function removeRequirementType (Request $request, Biodata $biodata) {
        $biodata->requirement_types()->detach($request->requirement_type_id);

        return [
            'method' => 'remove'
        ];
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Biodata  $biodata
     * @return \Illuminate\Http\Response
     */
    public function show(Biodata $biodata)
    {
        //
        return view('biodata.show', [
            'biodata' => $biodata
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Biodata  $biodata
     * @return \Illuminate\Http\Response
     */
    public function edit(Biodata $biodata)
    {
        //
        return view('biodata.form', [
            'biodata' => $biodata
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Biodata  $biodata
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Biodata $biodata)
    {
        //
        // rules
        $rules = [
            'name' => 'required|unique:biodatas,name,' . $biodata->id
        ];

        if ($request->type == "radio")
            $rules['choices'] = 'required';

        // validations
        $validation = Validator::make($request->all(), $rules);

        // validation fails
        if ($validation->fails())
            return redirect()->back()->withInput($request->all())->withErrors($validation);

        // validation success
        if (!$request->placeholder || empty($request->placeholder))
            $request->placeholder = $request->name;


        // insert
        $action = $biodata->update([
            'name' => $request->name,
            'placeholder' => $request->placeholder,
            'type' => $request->type,
            'choices' => $request->choices,
            'attributes' => NULL
        ]);

        // success
        if ($action) {
//            return redirect()->route('administrator.biodatas.show', ['biodata' => $biodata->id])->with('msg', 'Form Biodata berhasil ditambahkan');
            return redirect()->back()->with('msg', 'Form Biodata berhasil ditambahkan');
        } else {
            return redirect()->back()->with('msgError', 'Form Biodata gagal ditambahkan. Silahkan coba kembali.');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Biodata  $biodata
     * @return \Illuminate\Http\Response
     */
    public function destroy(Biodata $biodata)
    {
        // validations
        if ($biodata->biodata_posts->count() > 0) {
            return response()->json([
                'msg' => 'Form biodata gagal dihapus karena memiliki persyaratan dari dinas'
            ], 401);
        } elseif ($biodata->main == 1) {
            return response()->json([
                'msg' => 'Form biodata gagal dihapus karena ini merupakan form biodata utama'
            ], 401);
        }

        //
        $biodata->delete();

        return response()->json([
            'msg' => $biodata->biodata_posts->count()
        ], 200);
    }
}

resources/views/biodata/index.blade.php
@extends('layouts.master')

@section('title')
    List Form Biodata
@endsection

@section('biodatas')
    active
@endsection

@section('breadcumb')
    <li class="breadcrumb-item"><a href="{{route('administrator.dashboard')}}">Dashboard</a></li>
    <li class="breadcrumb-item active">Form Biodata</li>
@endsection

@section('menu')
    <i class="fa fa-id-card"></i> Form Biodata
@endsection

@section('content')
    <div class="container-fluid">
        <div class="jumbotron d-flex align-items-center justify-content-center">
            <img src="{{asset('assets/img/ill-list.svg')}}" class="illustration mr-5" alt="">
            <div class="col-md-5">
                <h4 class="mb-3">List Form Biodata</h4>
                <p style="margin-bottom: 0px;" class="text-muted">
                    Dibawah kamu dapat melihat list form biodata. Kamu dapat menambah, mengedit, menghapus, serta melihat detail dari form biodata.
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header align-items-center justify-content-between" style="display: grid; grid-template-columns: repeat(2, auto)">
                        <h3 class="card-title">List Form Biodata</h3>
                        <a href="{{ route('administrator.biodatas.create') }}" class="text-bold btn text-primary" style="background: #f5f6fb;"><i class="fa fa-plus-circle mr-1"></i> Tambah Form Biodata</a>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example1" class="table table-striped">
                            <thead>
                            <tr>
                                <th>No</th>
                                <th>Nama Form</th>
                                <th>Placeholder</th>
                                <th class="text-center">Aksi</th>
                            </tr>
                            </thead>
                            <tbody>
                                @foreach($biodatas as $i => $biodata)
                                    <tr>
                                        <td>{{$i+1}}</td>
                                        <td>{{$biodata->name}}</td>
                                        <td>{{$biodata->placeholder}}</td>
                                        <td class="text-center">
                                            <a href="{{route('administrator.biodatas.destroy', ['biodata' => $biodata->id])}}" class="text-danger mr-3 btn-delete" title="Delete" data-toggle="tooltip">
                                                <i class="fa fa-trash mr-1"></i> Hapus
                                            </a>
                                            <a href="{{route('administrator.biodatas.edit', ['biodata' => $biodata->id])}}" class="text-warning mr-3" title="Edit" data-toggle="tooltip">
                                                <i class="fa fa-edit mr-1"></i> Edit
                                            </a>
                                            <a href="{{route('administrator.biodatas.show', ['biodata' => $biodata->id])}}" class="btn btn-sm btn-default" title="List formulir" data-toggle="tooltip">
                                                <i class="fa fa-check-square mr-1"></i> Seleksi persyaratan
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
        </div>
    </div>
@endsection

@section('css')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{asset('assets/plugins/datatables-bs4/css/dataTables.bootstrap4.css')}}">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.1/css/buttons.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.1/css/buttons.bootstrap4.min.css">
@endsection

@section('js')
    <!-- DataTables -->
    <script src="{{asset('assets/plugins/datatables/jquery.dataTables.js')}}"></script>
    <script src="{{asset('assets/plugins/datatables-bs4/js/dataTables.bootstrap4.js')}}"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.print.min.js"></script>
    <!-- page script -->
    <script>
        $(function () {
            $("#example1").DataTable({
                dom: 'Bfrtip',
                buttons: [
                    'copy', 'csv', 'excel', 'pdf', 'print'
                ]
            });
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
            });
        });
    </script>
@endsection

resources/views/biodata/show.blade.php
@extends('layouts.master')

@section('title')
    Seleksi Form Biodata {{$biodata->name}}
@endsection

@section('biodatas')
    active
@endsection

@section('menu')
    <i class="fa fa-id-card mr-2"></i> Form Biodata <span class="text-info">{{$biodata->name}}</span>
@endsection

@section('breadcumb')
    <li class="breadcrumb-item"><a href="{{route('administrator.dashboard')}}">Dashboard</a></li>
    <li class="breadcrumb-item active"><a href="{{route('administrator.biodatas.index')}}">Form Biodata</a></li>
    <li class="breadcrumb-item active">{{$biodata->name}}</li>
@endsection

@section('content')
    <div class="container-fluid">
        @if(session('msg'))
            <div class="alert alert-success">
                {{session('msg')}}
            </div>
        @endif

        <div class="jumbotron d-flex align-items-center justify-content-center">
            <img src="{{asset('assets/img/illustration-13.svg')}}" class="illustration mr-5" alt="">
            <div class="col-md-5">
                <h4 class="mb-3">Form biodata <span class="text-info">{{$biodata->name}}</span></h4>
                <p style="margin-bottom: 0px;" class="text-muted">
                    Seleksi Tipe persyaratan yang akan menggunakan biodata <span class="text-info">{{$biodata->name}}</span> dibawah sesuai dengan apa yang kamu inginkan.
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="card card-default">
                    <div class="card-header">
                        <h3 class="card-title">
                            Seleksi Tipe Persyaratan
                        </h3>
                    </div>
                    <div class="card-body">
                        @foreach(\App\RequirementType::get()->chunk(3) as $requirementTypes)
                            <div class="row">
                                @foreach($requirementTypes as $requirementType)
                                    <div class="col-md-4 form-group clearfix">
                                        <div class="icheck-primary d-inline">
                                            <input type="checkbox" id="checkbox-{{$requirementType->id}}" class="biodata" value="{{$requirementType->id}}" {{$requirementType->biodatas()->whereBiodataId($biodata->id)->first() ? 'checked' : ''}}>
                                            <label for="checkbox-{{$requirementType->id}}">
                                            </label>
                                        </div>
                                        {{$requirementType->name}}
                                    </div>
                                @endforeach
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('css')
    <!-- iCheck for checkboxes and radio inputs -->
    <link rel="stylesheet" href="{{asset('assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css')}}">
@endsection

@section('js')

    <script>
        $( function() {
            let token = $('meta[name="csrf-token"]').attr('content');

            $('.biodata').click(function () {
                let url, data = {
                    _token: token,
                    requirement_type_id: $(this).val()
                };

                if ($(this).is(':checked')) {
                    url = '{{route('administrator.biodatas.addRequirementType', ['biodata' => $biodata->id])}}';
                } else {
                    url = '{{route('administrator.biodatas.removeRequirementType', ['biodata' => $biodata->id])}}';
                    data._method = "DELETE";
                }

                $.ajax({
                    url,
                    method: 'post',
                    data,
                    success: function (response) {
                        console.log(response);
                    },
                    error: function (errors) {
                        alert('error');
                    }
                })
            })
        } );
    </script>
    <!-- page script -->
@endsection